addons:
  apt:
    padkages:
      - docker-ce

sudo: required

services:
  - docker

before_install:
  - docker --version
  - make

script:
  - make test

after_success:
  - set -eux; echo "This branch is ${TRAVIS_BRANCH}"
  - set -eux; [ "$TRAVIS_BRANCH" = "master" ] && echo "== This is master" || echo "-- This is NOT master"
