addons:
  apt:
    padkages:
      - docker-ce

sudo: required

services:
  - docker

before_install:
  - docker --version
  - make

script:
  - make test

after_success:
  - set -eux; echo $TRAVIS_BRANCH
