addons:
  apt:
    padkages:
      - docker-ce

sudo: required

services:
  - docker

before_install:
  - docker --version
  - make

script:
  - make test

after_success:
  - echo "This branch is ${TRAVIS_BRANCH}"
  - set -x; if [ "$TRAVIS_BRANCH" = "master" ]; then echo "This"; echo "is"; echo "master"; echo "branch"; else echo "This is NOT master branch"; fi
